# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField()),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('journal', models.CharField(blank=True, max_length=30)),
                ('year', models.DateField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, to='expdata_interface.Author')),
                ('mesh', models.ManyToManyField(blank=True, to='expdata_interface.Mesh')),
            ],
        ),
    ]
