# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pmid', models.IntegerField()),
                ('journal', models.CharField(blank=True, max_length=30)),
                ('year', models.DateField(blank=True)),
                ('volume', models.IntegerField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('author', models.ManyToManyField(to='expdata_interface.Author')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Publication_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=30)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expdata_interface.Publication')),
            ],
        ),
        migrations.CreateModel(
            name='Publication_figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_name', models.CharField(max_length=30)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expdata_interface.Publication')),
                ('related_data', models.ManyToManyField(blank=True, to='expdata_interface.Publication_data')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
