# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0002_auto_20170426_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
