# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0003_auto_20170426_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
