# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0005_auto_20170427_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.ManyToManyField(blank=True, to='expdata_interface.Author'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
