# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0006_auto_20170427_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
