# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expdata_interface', '0008_auto_20170427_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='expdata_interface.Keywords'),
        ),
    ]
